// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrhrmcmdvscbktgqwfuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaHJtY21kdnNjYmt0Z3F3ZnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODk1MDksImV4cCI6MjA2MjY2NTUwOX0.jhYKnIN6Bryufv7bZU4ceVqFRNDYKnxePpdGdav9QO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);